package tech.ula.utils

import android.content.Context
import android.os.Build
import com.termux.terminal.TerminalSession
import java.io.File

/**
 * Creates a shell session that runs directly on the Android device.
 *
 * No proot, no root filesystem, no download. The shell is Android's own
 * /system/bin/sh started inside the app's sandbox, which means it can read
 * and write the app's private directories and shared storage, but not other
 * apps' data. Where the device supplies a working `su`, the shell is elevated
 * to root automatically.
 *
 * The busybox binary shipped in the APK is exported to the app's files
 * directory and prepended to PATH, so the session provides GNU-style
 * coreutils (grep, sed, awk, tar, find, vi, wget ...) rather than only
 * Android's stripped-down toybox.
 */
class AndroidShellLauncher(
    private val context: Context,
    private val ulaFiles: UlaFiles,
    private val logger: Logger = SentryLogger()
) {

    /** True when the created session was successfully elevated with `su`. */
    var usingRoot = false
        private set

    private val shellHome: File by lazy {
        File(context.filesDir, "android-home").also { it.mkdirs() }
    }

    private val busyboxToolbox: File by lazy {
        File(context.filesDir, "android-bin").also { it.mkdirs() }
    }

    /**
     * Populate a directory of busybox applet symlinks so the applets can be
     * invoked by their normal names.
     */
    private fun setupBusyboxToolbox() {
        val busybox = ulaFiles.busybox
        if (!busybox.exists()) return

        val marker = File(busyboxToolbox, ".installed")
        if (marker.exists()) return

        val applets = listOf(
                "awk", "basename", "bunzip2", "bzip2", "cpio", "cut", "diff", "dirname",
                "du", "env", "expr", "find", "free", "ftpget", "grep", "gunzip", "gzip",
                "head", "hexdump", "less", "md5sum", "nc", "nslookup", "od", "patch",
                "ping", "printf", "ps", "sed", "seq", "sha1sum", "sha256sum", "sort",
                "stat", "tail", "tar", "tee", "telnet", "test", "tftp", "time", "top",
                "tr", "traceroute", "uniq", "unzip", "vi", "wc", "wget", "which",
                "whoami", "xargs", "yes"
        )

        for (applet in applets) {
            val link = File(busyboxToolbox, applet)
            if (link.exists()) continue
            try {
                android.system.Os.symlink(busybox.absolutePath, link.absolutePath)
            } catch (err: Exception) {
                // A missing applet link is not fatal; the shell still works.
            }
        }
        try { marker.createNewFile() } catch (err: Exception) { }
    }

    /**
     * Returns true if the device provides a `su` binary that actually grants root.
     */
    private fun rootIsAvailable(): Boolean {
        val candidates = listOf(
                "/system/bin/su", "/system/xbin/su", "/sbin/su",
                "/system/sbin/su", "/vendor/bin/su", "/su/bin/su"
        )
        if (candidates.none { File(it).exists() }) return false

        return try {
            val process = ProcessBuilder("su", "-c", "id -u")
                    .redirectErrorStream(true)
                    .start()
            val output = process.inputStream.bufferedReader().readText().trim()
            process.waitFor()
            output.contains("0")
        } catch (err: Exception) {
            false
        }
    }

    private fun buildEnvironment(): Array<String> {
        val path = listOf(
                busyboxToolbox.absolutePath,
                ulaFiles.supportDir.absolutePath,
                "/system/bin",
                "/system/xbin",
                "/vendor/bin"
        ).joinToString(":")

        return arrayOf(
                "TERM=xterm-256color",
                "HOME=${shellHome.absolutePath}",
                "PATH=$path",
                "LANG=en_US.UTF-8",
                "TMPDIR=${File(context.cacheDir, "shell").apply { mkdirs() }.absolutePath}",
                "SHELL=/system/bin/sh",
                "ANDROID_ROOT=${System.getenv("ANDROID_ROOT") ?: "/system"}",
                "ANDROID_DATA=${System.getenv("ANDROID_DATA") ?: "/data"}",
                "EXTERNAL_STORAGE=${System.getenv("EXTERNAL_STORAGE") ?: "/sdcard"}",
                "BUSYBOX=${ulaFiles.busybox.absolutePath}",
                "APP_FILES=${context.filesDir.absolutePath}",
                "DEVICE=${Build.MODEL}",
                "ANDROID_VERSION=${Build.VERSION.RELEASE}"
        )
    }

    /**
     * Writes a small login banner and rc file so the session is self-describing.
     */
    private fun setupRcFile(): File {
        val rc = File(shellHome, ".shrc")
        rc.writeText("""
            # Generated by UserLAnd Terminal for the on-device Android shell.
            export PS1='\[\e[32m\]android\[\e[0m\]:\w \$ '
            alias ll='ls -la'
            alias la='ls -a'
            echo "UserLAnd Terminal - Android shell"
            echo "Device: ${Build.MODEL} (Android ${Build.VERSION.RELEASE}, API ${Build.VERSION.SDK_INT})"
            echo "Home: ${shellHome.absolutePath}"
            echo "Busybox utilities are on PATH. Type 'busybox --list' to see all applets."
            echo ""
        """.trimIndent())
        return rc
    }

    /** Launch a selected Linux filesystem directly in TerminalSession's PTY. */
    fun createProotSession(callback: TerminalSession.SessionChangedCallback, filesystemId: Long, username: String): TerminalSession? {
        return try {
            val rootfs = File(context.filesDir, filesystemId.toString())
            val env = buildEnvironment().toMutableList()
            env += "ROOT_PATH=${context.filesDir.absolutePath}"
            env += "ROOTFS_PATH=${rootfs.absolutePath}"
            env += "LIB_PATH=${ulaFiles.supportDir.absolutePath}"
            env += "LD_LIBRARY_PATH=${ulaFiles.supportDir.absolutePath}"
            env += "PROOT_DEBUG_LEVEL=-1"
            env += "PROOT_ID=-i 2000:2000"
            env += "EXTRA_BINDINGS=-b ${ulaFiles.emulatedUserDir.absolutePath}:/storage/internal"
            env += "OS_VERSION=${System.getProperty("os.version") ?: ""}"
            val starter = File(rootfs, "support/direct-local-shell.sh")
            starter.parentFile?.mkdirs()
            starter.writeText("#!/bin/sh\nexport HOME=/home/" + username +
                    "\nexec /bin/bash --rcfile /home/" + username + "/.bashrc -i\n")
            starter.setExecutable(true, false)
            val session = TerminalSession(ulaFiles.busybox.absolutePath, rootfs.absolutePath,
                    arrayOf("busybox", "sh", File(ulaFiles.supportDir, "execInProot.sh").absolutePath,
                            "/support/direct-local-shell.sh"), env.toTypedArray(), callback)
            session.updateSize(80, 24)
            session
        } catch (err: Exception) {
            tech.ula.LocalSessionTrace.append(context, "LOCAL proot failure: ${err.javaClass.simpleName}: ${err.message}")
            null
        }
    }

    /**
     * Creates the terminal session. Returns null if no shell could be started.
     */
    fun createSession(callback: TerminalSession.SessionChangedCallback): TerminalSession? {
        return try {
            setupBusyboxToolbox()
            setupRcFile()

            val environment = buildEnvironment()
            usingRoot = rootIsAvailable()

            val shell = "/system/bin/sh"
            val rcPath = File(shellHome, ".shrc").absolutePath
            val args: Array<String> = if (usingRoot) {
                arrayOf("su", "-c", "$shell --rcfile $rcPath -i")
            } else {
                arrayOf("sh", "-i")
            }

            val executable = if (usingRoot) "/system/bin/su" else shell

            val session = TerminalSession(
                    executable,
                    shellHome.absolutePath,
                    args,
                    environment,
                    callback
            )
            session.updateSize(80, 24)
            session
        } catch (err: Exception) {
            logger.addExceptionBreadcrumb(Exception("Failed to start Android shell: ${err.message}"))
            null
        }
    }
}
